package cc.dmji.website.entity;

import java.util.Date;

public class Bangumi {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_bangumi.bangumi_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer bangumiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_bangumi.bangumi_name
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String bangumiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_bangumi.episode_total
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer episodeTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_bangumi.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_bangumi.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_bangumi.thumb
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String thumb;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_bangumi.bangumi_id
     *
     * @return the value of dm_bangumi.bangumi_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getBangumiId() {
        return bangumiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_bangumi.bangumi_id
     *
     * @param bangumiId the value for dm_bangumi.bangumi_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setBangumiId(Integer bangumiId) {
        this.bangumiId = bangumiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_bangumi.bangumi_name
     *
     * @return the value of dm_bangumi.bangumi_name
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getBangumiName() {
        return bangumiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_bangumi.bangumi_name
     *
     * @param bangumiName the value for dm_bangumi.bangumi_name
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setBangumiName(String bangumiName) {
        this.bangumiName = bangumiName == null ? null : bangumiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_bangumi.episode_total
     *
     * @return the value of dm_bangumi.episode_total
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getEpisodeTotal() {
        return episodeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_bangumi.episode_total
     *
     * @param episodeTotal the value for dm_bangumi.episode_total
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setEpisodeTotal(Integer episodeTotal) {
        this.episodeTotal = episodeTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_bangumi.create_time
     *
     * @return the value of dm_bangumi.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_bangumi.create_time
     *
     * @param createTime the value for dm_bangumi.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_bangumi.modify_time
     *
     * @return the value of dm_bangumi.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_bangumi.modify_time
     *
     * @param modifyTime the value for dm_bangumi.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_bangumi.thumb
     *
     * @return the value of dm_bangumi.thumb
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_bangumi.thumb
     *
     * @param thumb the value for dm_bangumi.thumb
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setThumb(String thumb) {
        this.thumb = thumb == null ? null : thumb.trim();
    }
}