package cc.dmji.website.entity;

import java.util.Date;

public class Episode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_episode.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer epId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_episode.ep_index
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer epIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_episode.bangumi_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer bangumiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_episode.replyable
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Boolean replyable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_episode.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_episode.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_episode.danmaku_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String danmakuId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_episode.ep_id
     *
     * @return the value of dm_episode.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_episode.ep_id
     *
     * @param epId the value for dm_episode.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setEpId(Integer epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_episode.ep_index
     *
     * @return the value of dm_episode.ep_index
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getEpIndex() {
        return epIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_episode.ep_index
     *
     * @param epIndex the value for dm_episode.ep_index
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setEpIndex(Integer epIndex) {
        this.epIndex = epIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_episode.bangumi_id
     *
     * @return the value of dm_episode.bangumi_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getBangumiId() {
        return bangumiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_episode.bangumi_id
     *
     * @param bangumiId the value for dm_episode.bangumi_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setBangumiId(Integer bangumiId) {
        this.bangumiId = bangumiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_episode.replyable
     *
     * @return the value of dm_episode.replyable
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Boolean getReplyable() {
        return replyable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_episode.replyable
     *
     * @param replyable the value for dm_episode.replyable
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setReplyable(Boolean replyable) {
        this.replyable = replyable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_episode.create_time
     *
     * @return the value of dm_episode.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_episode.create_time
     *
     * @param createTime the value for dm_episode.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_episode.modify_time
     *
     * @return the value of dm_episode.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_episode.modify_time
     *
     * @param modifyTime the value for dm_episode.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_episode.danmaku_id
     *
     * @return the value of dm_episode.danmaku_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getDanmakuId() {
        return danmakuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_episode.danmaku_id
     *
     * @param danmakuId the value for dm_episode.danmaku_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setDanmakuId(String danmakuId) {
        this.danmakuId = danmakuId == null ? null : danmakuId.trim();
    }
}