package cc.dmji.website.entity;

import java.util.Date;

public class LoginRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_login_record.record_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String recordId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_login_record.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_login_record.user_agent
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String userAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_login_record.ip
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_login_record.address
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_login_record.isp
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String isp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_login_record.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_login_record.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_login_record.record_id
     *
     * @return the value of dm_login_record.record_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_login_record.record_id
     *
     * @param recordId the value for dm_login_record.record_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setRecordId(String recordId) {
        this.recordId = recordId == null ? null : recordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_login_record.user_id
     *
     * @return the value of dm_login_record.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_login_record.user_id
     *
     * @param userId the value for dm_login_record.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_login_record.user_agent
     *
     * @return the value of dm_login_record.user_agent
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_login_record.user_agent
     *
     * @param userAgent the value for dm_login_record.user_agent
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_login_record.ip
     *
     * @return the value of dm_login_record.ip
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_login_record.ip
     *
     * @param ip the value for dm_login_record.ip
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_login_record.address
     *
     * @return the value of dm_login_record.address
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_login_record.address
     *
     * @param address the value for dm_login_record.address
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_login_record.isp
     *
     * @return the value of dm_login_record.isp
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getIsp() {
        return isp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_login_record.isp
     *
     * @param isp the value for dm_login_record.isp
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setIsp(String isp) {
        this.isp = isp == null ? null : isp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_login_record.create_time
     *
     * @return the value of dm_login_record.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_login_record.create_time
     *
     * @param createTime the value for dm_login_record.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_login_record.modify_time
     *
     * @return the value of dm_login_record.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_login_record.modify_time
     *
     * @param modifyTime the value for dm_login_record.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}