package cc.dmji.website.entity;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.message_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String messageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.type
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer epId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.reply_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.is_read
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Boolean isRead;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.at_anchor
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String atAnchor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_message.m_status
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String mStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.message_id
     *
     * @return the value of dm_message.message_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.message_id
     *
     * @param messageId the value for dm_message.message_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.type
     *
     * @return the value of dm_message.type
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.type
     *
     * @param type the value for dm_message.type
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.ep_id
     *
     * @return the value of dm_message.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.ep_id
     *
     * @param epId the value for dm_message.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setEpId(Integer epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.reply_id
     *
     * @return the value of dm_message.reply_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.reply_id
     *
     * @param replyId the value for dm_message.reply_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setReplyId(String replyId) {
        this.replyId = replyId == null ? null : replyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.is_read
     *
     * @return the value of dm_message.is_read
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.is_read
     *
     * @param isRead the value for dm_message.is_read
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.user_id
     *
     * @return the value of dm_message.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.user_id
     *
     * @param userId the value for dm_message.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.at_anchor
     *
     * @return the value of dm_message.at_anchor
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getAtAnchor() {
        return atAnchor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.at_anchor
     *
     * @param atAnchor the value for dm_message.at_anchor
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setAtAnchor(String atAnchor) {
        this.atAnchor = atAnchor == null ? null : atAnchor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.create_time
     *
     * @return the value of dm_message.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.create_time
     *
     * @param createTime the value for dm_message.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.modify_time
     *
     * @return the value of dm_message.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.modify_time
     *
     * @param modifyTime the value for dm_message.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_message.m_status
     *
     * @return the value of dm_message.m_status
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getmStatus() {
        return mStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_message.m_status
     *
     * @param mStatus the value for dm_message.m_status
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setmStatus(String mStatus) {
        this.mStatus = mStatus == null ? null : mStatus.trim();
    }
}