package cc.dmji.website.entity;

import java.util.Date;

public class Reply {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.reply_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer epId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.r_page
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer rPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.r_status
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String rStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.parent_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.is_parent
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Boolean isParent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.r_like
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer rLike;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.r_hate
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer rHate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_reply.content
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.reply_id
     *
     * @return the value of dm_reply.reply_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.reply_id
     *
     * @param replyId the value for dm_reply.reply_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setReplyId(String replyId) {
        this.replyId = replyId == null ? null : replyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.ep_id
     *
     * @return the value of dm_reply.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.ep_id
     *
     * @param epId the value for dm_reply.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setEpId(Integer epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.r_page
     *
     * @return the value of dm_reply.r_page
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getrPage() {
        return rPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.r_page
     *
     * @param rPage the value for dm_reply.r_page
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setrPage(Integer rPage) {
        this.rPage = rPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.create_time
     *
     * @return the value of dm_reply.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.create_time
     *
     * @param createTime the value for dm_reply.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.modify_time
     *
     * @return the value of dm_reply.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.modify_time
     *
     * @param modifyTime the value for dm_reply.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.user_id
     *
     * @return the value of dm_reply.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.user_id
     *
     * @param userId the value for dm_reply.user_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.r_status
     *
     * @return the value of dm_reply.r_status
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getrStatus() {
        return rStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.r_status
     *
     * @param rStatus the value for dm_reply.r_status
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setrStatus(String rStatus) {
        this.rStatus = rStatus == null ? null : rStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.parent_id
     *
     * @return the value of dm_reply.parent_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.parent_id
     *
     * @param parentId the value for dm_reply.parent_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.is_parent
     *
     * @return the value of dm_reply.is_parent
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Boolean getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.is_parent
     *
     * @param isParent the value for dm_reply.is_parent
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setIsParent(Boolean isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.r_like
     *
     * @return the value of dm_reply.r_like
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getrLike() {
        return rLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.r_like
     *
     * @param rLike the value for dm_reply.r_like
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setrLike(Integer rLike) {
        this.rLike = rLike;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.r_hate
     *
     * @return the value of dm_reply.r_hate
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getrHate() {
        return rHate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.r_hate
     *
     * @param rHate the value for dm_reply.r_hate
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setrHate(Integer rHate) {
        this.rHate = rHate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_reply.content
     *
     * @return the value of dm_reply.content
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_reply.content
     *
     * @param content the value for dm_reply.content
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}