package cc.dmji.website.entity;

import java.util.Date;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_video.video_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_video.v_md5
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private String vMd5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_video.file_size
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Long fileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_video.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Integer epId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_video.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dm_video.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_video.video_id
     *
     * @return the value of dm_video.video_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_video.video_id
     *
     * @param videoId the value for dm_video.video_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_video.v_md5
     *
     * @return the value of dm_video.v_md5
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public String getvMd5() {
        return vMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_video.v_md5
     *
     * @param vMd5 the value for dm_video.v_md5
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setvMd5(String vMd5) {
        this.vMd5 = vMd5 == null ? null : vMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_video.file_size
     *
     * @return the value of dm_video.file_size
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_video.file_size
     *
     * @param fileSize the value for dm_video.file_size
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_video.ep_id
     *
     * @return the value of dm_video.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Integer getEpId() {
        return epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_video.ep_id
     *
     * @param epId the value for dm_video.ep_id
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setEpId(Integer epId) {
        this.epId = epId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_video.create_time
     *
     * @return the value of dm_video.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_video.create_time
     *
     * @param createTime the value for dm_video.create_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dm_video.modify_time
     *
     * @return the value of dm_video.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dm_video.modify_time
     *
     * @param modifyTime the value for dm_video.modify_time
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}