package cc.dmji.website.dao;

import cc.dmji.website.entity.Bangumi;
import cc.dmji.website.entity.BangumiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BangumiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    long countByExample(BangumiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByExample(BangumiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByPrimaryKey(Integer bangumiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insert(Bangumi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insertSelective(Bangumi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    List<Bangumi> selectByExample(BangumiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    Bangumi selectByPrimaryKey(Integer bangumiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Bangumi record, @Param("example") BangumiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExample(@Param("record") Bangumi record, @Param("example") BangumiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKeySelective(Bangumi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_bangumi
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKey(Bangumi record);
}