package cc.dmji.website.dao;

import cc.dmji.website.entity.Episode;
import cc.dmji.website.entity.EpisodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EpisodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    long countByExample(EpisodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByExample(EpisodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByPrimaryKey(Integer epId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insert(Episode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insertSelective(Episode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    List<Episode> selectByExample(EpisodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    Episode selectByPrimaryKey(Integer epId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Episode record, @Param("example") EpisodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExample(@Param("record") Episode record, @Param("example") EpisodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKeySelective(Episode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_episode
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKey(Episode record);
}