package cc.dmji.website.dao;

import cc.dmji.website.entity.LoginRecord;
import cc.dmji.website.entity.LoginRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    long countByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insert(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insertSelective(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    List<LoginRecord> selectByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    LoginRecord selectByPrimaryKey(String recordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoginRecord record, @Param("example") LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExample(@Param("record") LoginRecord record, @Param("example") LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKeySelective(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_login_record
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKey(LoginRecord record);
}