package cc.dmji.website.dao;

import cc.dmji.website.entity.Reply;
import cc.dmji.website.entity.ReplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    long countByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByPrimaryKey(String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insert(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insertSelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    List<Reply> selectByExampleWithBLOBs(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    List<Reply> selectByExample(ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    Reply selectByPrimaryKey(String replyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExample(@Param("record") Reply record, @Param("example") ReplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKeySelective(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Reply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_reply
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKey(Reply record);
}