package cc.dmji.website.dao;

import cc.dmji.website.entity.Video;
import cc.dmji.website.entity.VideoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    long countByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int deleteByPrimaryKey(String videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insert(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int insertSelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    List<Video> selectByExample(VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    Video selectByPrimaryKey(String videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") Video record, @Param("example") VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByExample(@Param("record") Video record, @Param("example") VideoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKeySelective(Video record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dm_video
     *
     * @mbg.generated Tue May 08 23:01:05 CST 2018
     */
    int updateByPrimaryKey(Video record);
}